// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiOrkhan.Data;

namespace WebApiOrkhan.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20201215012215_Variant4")]
    partial class Variant4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CategoryMaterial", b =>
                {
                    b.Property<int>("Categoryid")
                        .HasColumnType("integer");

                    b.Property<int>("Materialsid")
                        .HasColumnType("integer");

                    b.HasKey("Categoryid", "Materialsid");

                    b.HasIndex("Materialsid");

                    b.ToTable("CategoryMaterial");
                });

            modelBuilder.Entity("WebApi5.Data.Models.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("material_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("material_name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("WebApiOrkhan.Data.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("category_name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CategoryMaterial", b =>
                {
                    b.HasOne("WebApiOrkhan.Data.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi5.Data.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("Materialsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
