// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiOrkhan.Data;

namespace WebApiOrkhan.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20201215020052_Variant1")]
    partial class Variant1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("WebApi5.Data.Models.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("category_type")
                        .HasColumnType("text");

                    b.Property<DateTime>("material_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("material_name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("WebApiOrkhan.Data.Models.File", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("file_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("file_name")
                        .HasColumnType("text");

                    b.Property<int?>("materialid")
                        .HasColumnType("integer");

                    b.Property<string>("path_of_file")
                        .HasColumnType("text");

                    b.Property<long>("size")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("materialid");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("WebApiOrkhan.Data.Models.File", b =>
                {
                    b.HasOne("WebApi5.Data.Models.Material", "material")
                        .WithMany("Files")
                        .HasForeignKey("materialid");

                    b.Navigation("material");
                });

            modelBuilder.Entity("WebApi5.Data.Models.Material", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
