// <auto-generated />
using System;
using BabaevTask5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BabaevTask5.Migrations
{
    [DbContext(typeof(AppDbContent))]
    [Migration("20201228224407_migrInit")]
    partial class migrInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BabaevTask5.Data.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryType")
                        .HasColumnType("text");

                    b.Property<DateTime>("MaterialDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MaterialName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("BabaevTask5.Data.Models.MaterialVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FileDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("PathOfFile")
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialVersions");
                });

            modelBuilder.Entity("BabaevTask5.Data.Models.MaterialVersion", b =>
                {
                    b.HasOne("BabaevTask5.Data.Models.Material", "Material")
                        .WithMany("MaterialVersions")
                        .HasForeignKey("MaterialId");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("BabaevTask5.Data.Models.Material", b =>
                {
                    b.Navigation("MaterialVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
